// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtFNoHT3uy3deZ2J23DkMg_Jm0EdPM0-8',
    appId: '1:663058938656:web:ed6797bcf8a682ab0e3545',
    messagingSenderId: '663058938656',
    projectId: 'avances-login',
    authDomain: 'avances-login.firebaseapp.com',
    databaseURL: 'https://avances-login-default-rtdb.firebaseio.com',
    storageBucket: 'avances-login.firebasestorage.app',
    measurementId: 'G-5V7WQ4NL57',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxq6EhqQARYdtY3LMyXC5b0OTyEPSIJwU',
    appId: '1:663058938656:android:b2a55ec0f618d30a0e3545',
    messagingSenderId: '663058938656',
    projectId: 'avances-login',
    databaseURL: 'https://avances-login-default-rtdb.firebaseio.com',
    storageBucket: 'avances-login.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYQCE0yNl3O7-ZQHIUwULQxxlHS99JynA',
    appId: '1:663058938656:ios:804bfb5d07def3790e3545',
    messagingSenderId: '663058938656',
    projectId: 'avances-login',
    databaseURL: 'https://avances-login-default-rtdb.firebaseio.com',
    storageBucket: 'avances-login.firebasestorage.app',
    androidClientId: '663058938656-v5n2sn2dht7slrq67ekjlciagkeb5vu9.apps.googleusercontent.com',
    iosClientId: '663058938656-epfhmf0h4o270vqm0snqlecla64j6ifk.apps.googleusercontent.com',
    iosBundleId: 'com.example.avances',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYQCE0yNl3O7-ZQHIUwULQxxlHS99JynA',
    appId: '1:663058938656:ios:804bfb5d07def3790e3545',
    messagingSenderId: '663058938656',
    projectId: 'avances-login',
    databaseURL: 'https://avances-login-default-rtdb.firebaseio.com',
    storageBucket: 'avances-login.firebasestorage.app',
    androidClientId: '663058938656-v5n2sn2dht7slrq67ekjlciagkeb5vu9.apps.googleusercontent.com',
    iosClientId: '663058938656-epfhmf0h4o270vqm0snqlecla64j6ifk.apps.googleusercontent.com',
    iosBundleId: 'com.example.avances',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtFNoHT3uy3deZ2J23DkMg_Jm0EdPM0-8',
    appId: '1:663058938656:web:ccc900945b242e790e3545',
    messagingSenderId: '663058938656',
    projectId: 'avances-login',
    authDomain: 'avances-login.firebaseapp.com',
    databaseURL: 'https://avances-login-default-rtdb.firebaseio.com',
    storageBucket: 'avances-login.firebasestorage.app',
    measurementId: 'G-Z4HVJWY3QW',
  );

}